<?php
/**
 * @file
 * Code for the Stanford Related Events feature.
 */

include_once 'stanford_related_events.features.inc';


/**
 * Implements hook_views_default_views_alter().
 */
function stanford_related_events_views_default_views_alter(&$views) {
  stanford_related_events_alter_upcoming_block($views);
  stanford_related_events_alter_manage_events($views);

  // Add related content to the exposed filter
  stanford_related_content_add_exposed_filter($views, 'stanford_events_views', 'page');
  stanford_related_content_add_exposed_filter($views, 'stanford_events_views', 'upcoming_events_list_page');

}
/**
 * Add exposed filter for related content to the page display.
 *
 * @param object $views
 *   Array of views.
 * @param string $name
 *    View to be altered.
 */
function stanford_related_events_alter_manage_events(&$views) {
  $name = 'stanford_events_manage';
  if (array_key_exists($name, $views)) {
    $view = $views[$name];
  }
  else {
    return FALSE;
  }

  if ($view->set_display('page')) {
    $handler = $view->display_handler;
  }
  else {
    watchdog('stanford_related_events', "Display 'page' not available in view %name.",
      array('%name' => $name), WATCHDOG_NOTICE);
    return FALSE;
  }

  /**
   * Add event series column to manage events view.
   * @var [type]
   */
  /*
  if ($view->name == 'stanford_events_manage' && $view->current_display == "page") {

    // Get all of the page fields.
    $items = $view->get_items("field", "page");

    // Let us re-arrange the fields.
    foreach ($items as $field_name => $value) {

      // Got to remove the item to change the order.
      $view->set_item("page", "field", $field_name, NULL);

      // If the field is the event type field we want to insert the series after.
      if ($field_name == "field_s_event_type") {
        // Set the event field type first.
        $view->set_item("page", "field", $field_name, $value);

        // Then create the multiple value field using UL list.
        $view->add_item($view->current_display, 'field', 'field_data_field_s_event_series', 'field_s_event_series', array(
            'label' => t('Event series'),
            'element_default_classes' => 1,
            'element_label_colon' => 0,
            'hide_empty' => 1,
            'settings' => array(
              'link' => 1,
            ),
            'group_type' => "group",
            'group_rows' => 1,
            'multi_type' => "ul",
          ),
          'field_s_event_series');

        continue;
      }

      // All other items just get saved in the same order.
      $view->set_item("page", "field", $field_name, $value);

    }

  }
*/
  // Add filter.
  $options = $handler->get_option('filters');
  $options['term_node_tid_depth']['id'] = 'term_node_tid_depth';
  $options['term_node_tid_depth']['table'] = 'node';
  $options['term_node_tid_depth']['field'] = 'term_node_tid_depth';
  $options['term_node_tid_depth']['exposed'] = TRUE;
  $options['term_node_tid_depth']['expose']['operator_id'] = 'term_node_tid_depth_op';
  $options['term_node_tid_depth']['expose']['label'] = 'Filter by related content';
  $options['term_node_tid_depth']['expose']['operator'] = 'term_node_tid_depth_op';
  $options['term_node_tid_depth']['expose']['identifier'] = 'term_node_tid_depth';
  $options['term_node_tid_depth']['expose']['multiple'] = FALSE;
  $options['term_node_tid_depth']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    6 => 0,
    5 => 0,
    4 => 0,
    3 => 0,
    9 => 0,
    7 => 0,
    8 => 0,
  );
  $options['term_node_tid_depth']['type'] = 'select';
  $options['term_node_tid_depth']['vocabulary'] = 'stanford_related_content';
  $options['term_node_tid_depth']['hierarchy'] = 1;
  $options['term_node_tid_depth']['depth'] = '0';
  $handler->set_option('filters', $options);

  // Add Field: Content: Related Content.
  $options = $handler->get_option('fields');
  $options['field_s_related_content']['id'] = 'field_s_related_content';
  $options['field_s_related_content']['table'] = 'field_data_field_s_related_content';
  $options['field_s_related_content']['field'] = 'field_s_related_content';
  $options['field_s_related_content']['type'] = 'taxonomy_term_reference_plain';
  $options['field_s_related_content']['delta_offset'] = '0';
  $options['field_s_related_content']['multi_type'] = 'ul';

  // Add VBO option.
  // VBO 7.x-3.2
  if (isset($options['views_bulk_operations']['vbo_operations']['action::views_bulk_operations_modify_action']
  ['settings'])) {
    $options['views_bulk_operations']['vbo_operations']['action::views_bulk_operations_modify_action']
      ['settings']['display_values']['stanford_event::field_s_related_content'] = 'stanford_event::field_s_related_content';
  }

  // VBO 7.x-3.0-rc1
  elseif (is_array($options['views_bulk_operations']['vbo']['operations']['action::views_bulk_operations_modify_action']
  ['settings']['display_values'])){
    $options['views_bulk_operations']['vbo']['operations']['action::views_bulk_operations_modify_action']
     ['settings']['display_values']['stanford_event::field_s_related_content'] = 'stanford_event::field_s_related_content';
  }
  else {
    $options['views_bulk_operations']['vbo_operations']['action::views_bulk_operations_modify_action'] =
       array(
        'selected' => 1,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 1,
        'label' => 'Modify',
        'settings' => array(
          'show_all_tokens' => 0,
          'display_values' => array(
            'stanford_event::field_s_event_type' => 'stanford_event::field_s_event_type',
            'stanford_event::field_s_related_content' => 'stanford_event::field_s_related_content',
          ),
        ),
      );
  }


  $handler->set_option('fields', $options);

  // Check that the view still works after we altered it!
  if (stanford_related_content_validate_view($views[$name], 'stanford_related_events')) {
    watchdog($name, "Filter 'field_s_related_content' added to  view %name.",
      array('%name' => $name), WATCHDOG_DEBUG);
    return TRUE;
  }
  return FALSE;
}


/**
 * Copy the block display in the stanford_events_view and add contextual filter.
 *
 * @param object $views
 *   Array of views.
 * @param string $name
 *    View to be altered.
 */
function stanford_related_events_alter_upcoming_block(&$views) {
  $name = 'stanford_events_views';
  if (array_key_exists($name, $views)) {
    $view = $views[$name];
  }
  else {
    watchdog('stanford_related_events', "View '%name' not available.",
      array('%name' => $name), WATCHDOG_NOTICE);
    return FALSE;
  }

  // Get the page URL
  if ($view->set_display('page')) {
    $page_handler = $view->display_handler;
  }
  else {
    watchdog('stanford_related_events', "Display 'page' not available in view %name.",
      array('%name' => $name), WATCHDOG_NOTICE);
    return FALSE;
  }

  $page_path = $page_handler->get_option('path');

  // Copy the block display.
  $display_id_orig = 'block';

  if ($view->set_display($display_id_orig)) {
    $display_orig = $view->display_handler;
  }
  else {
    watchdog('stanford_related_events', "Display %display_id_orig not available in view %name.",
      array('%display_id_orig' => $display_id_orig, '%name' => $name), WATCHDOG_NOTICE);
    return FALSE;
  }

  // Get the display options.
  if (isset($display_orig->handler->display->display_options)) {
    $options_orig = $display_orig->handler->display->display_options;
  }
  elseif (isset($display_orig->display->display_options)) {
    $options_orig = $display_orig->display->display_options;
  }
  else {
    watchdog('stanford_related_events', "Display options for display %display_id_orig not available in view %name.",
      array('%display_id_orig' => $display_id_orig, '%name' => $name), WATCHDOG_NOTICE);
    return FALSE;
  }

  // Copy the display options.
  $handler = $view->new_display('block', 'Filtered Upcoming Block', 'filtered_upcoming_block');
  foreach ($options_orig as $key => $value) {
    $handler->set_option($key, $value);
  }

  // Override defaults.
  $options = $handler->get_option('defaults');
  $options['arguments'] = FALSE;
  $options['link_display'] = FALSE;
  $options['footer'] = FALSE;

  // No results behavior: Override so nothing displays.
  $options['empty'] = FALSE;

  $handler->set_option('defaults', $options);

  // Add the contextual filter.

  $options = $handler->get_option('arguments');
  $options['term_node_tid_depth']['id'] = 'term_node_tid_depth';
  $options['term_node_tid_depth']['table'] = 'node';
  $options['term_node_tid_depth']['field'] = 'term_node_tid_depth';
  $options['term_node_tid_depth']['default_action'] = 'default';
  $options['term_node_tid_depth']['title_enable'] = TRUE;
  $options['term_node_tid_depth']['title'] = 'Related Upcoming Events ';
  $options['term_node_tid_depth']['default_argument_type'] = 'taxonomy_tid';
  $options['term_node_tid_depth']['default_argument_options']['node'] = TRUE;
  $options['term_node_tid_depth']['default_argument_options']['anyall'] = '+';
  $options['term_node_tid_depth']['default_argument_options']['vocabularies'] = array(
    'stanford_related_content' => 'stanford_related_content',
  );
  $options['term_node_tid_depth']['summary']['number_of_records'] = '0';
  $options['term_node_tid_depth']['summary']['format'] = 'default_summary';
  $options['term_node_tid_depth']['summary_options']['items_per_page'] = '25';
  $options['term_node_tid_depth']['specify_validation'] = TRUE;
  $options['term_node_tid_depth']['depth'] = '0';
  $options['term_node_tid_depth']['break_phrase'] = TRUE;

  $handler->set_option('arguments', $options);

  $handler->set_option('use_more', FALSE);
  $handler->set_option('use_more_always', FALSE);

  // Footer: Global: See more link.
  $options = $handler->get_option('footer');
  $options['area']['id'] = 'area';
  $options['area']['table'] = 'views';
  $options['area']['field'] = 'area';
  $options['area']['ui_name'] = 'Global: See more link';
  $options['area']['content'] = '[hook_views_pre_build:' . $page_path . ']';
  $options['area']['format'] = 'content_editor_text_format';
  $options['area']['tokenize'] = TRUE;

  $handler->set_option('footer', $options);




  // Check that the view still works after we altered it!
  if (stanford_related_content_validate_view($views[$name], 'stanford_related_events')) {
    watchdog($name, "Block 'filtered_upcoming_block' added to view %name.",
      array('%name' => $name), WATCHDOG_DEBUG);
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_views_pre_build().
 *
 *   This rewrites the pattern in the footer of the view and replaces it
 *   with a link to the related view page.
 */
function stanford_related_events_views_pre_build(&$view) {
  if (($view->name == "stanford_events_views") || ($view->name == "stanford_events_views_override")) {
    if (($view->current_display == "filtered_upcoming_block") ||
      ($view->current_display == "block_5")) {
      $subject = $view->footer["area"]->options["content"];
      $view->footer["area"]->options["content"] = stanford_related_content_add_more_link($subject, "See more related events");
    }
  }
}
