<?php
/**
 * @file
 * Code for the Stanford Related Events feature.
 */

include_once 'stanford_related_events.features.inc';

function stanford_related_events_form_alter(&$form, &$form_state, $form_id) {
  dpm($form_id);
}


/*
 * Implements hook_views_default_views_alter().
 */
function stanford_related_events_views_default_views_alter(&$views) {

  if (array_key_exists('stanford_events_views', $views)) {
    stanford_related_events_alter_upcoming_block($views['stanford_events_views']);
    stanford_related_events_alter_upcoming_page($views['stanford_events_views']);
  }
}
/*
 * Add contextual filter for related content to the page display
 */
function stanford_related_events_alter_upcoming_page(&$view){

  $handler = $view->display['page']->handler;

  /* Filter criterion: Content: Has taxonomy terms (with depth) */

  $handler->display->display_options['filters']['term_node_tid_depth']['id'] = 'term_node_tid_depth';
  $handler->display->display_options['filters']['term_node_tid_depth']['table'] = 'node';
  $handler->display->display_options['filters']['term_node_tid_depth']['field'] = 'term_node_tid_depth';
  $handler->display->display_options['filters']['term_node_tid_depth']['exposed'] = TRUE;
  $handler->display->display_options['filters']['term_node_tid_depth']['expose']['operator_id'] = 'term_node_tid_depth_op';
  $handler->display->display_options['filters']['term_node_tid_depth']['expose']['label'] = 'Filter by related content';
  $handler->display->display_options['filters']['term_node_tid_depth']['expose']['operator'] = 'term_node_tid_depth_op';
  $handler->display->display_options['filters']['term_node_tid_depth']['expose']['identifier'] = 'term_node_tid_depth';
  $handler->display->display_options['filters']['term_node_tid_depth']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    6 => 0,
    5 => 0,
    4 => 0,
    3 => 0,
    9 => 0,
    7 => 0,
    8 => 0,
  );
  $handler->display->display_options['filters']['term_node_tid_depth']['type'] = 'select';
  $handler->display->display_options['filters']['term_node_tid_depth']['vocabulary'] = 'stanford_related_content';
  $handler->display->display_options['filters']['term_node_tid_depth']['hierarchy'] = 1;
  $handler->display->display_options['filters']['term_node_tid_depth']['depth'] = '0';

}

/*
 * Copy the block display in the stanford_events_view and add contextual filter for related content
 */
function stanford_related_events_alter_upcoming_block(&$view){

    $display_orig = $view->display['block'];
    $handler = $view->new_display('block', 'Filtered Upcoming Block', 'filtered_upcoming_block');

    foreach($display_orig->handler->display->display_options as $key => $value) {
      $handler->set_option($key, $value);
    }

  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Has taxonomy term ID (with depth) */
  $handler->display->display_options['arguments']['term_node_tid_depth']['id'] = 'term_node_tid_depth';
  $handler->display->display_options['arguments']['term_node_tid_depth']['table'] = 'node';
  $handler->display->display_options['arguments']['term_node_tid_depth']['field'] = 'term_node_tid_depth';
  $handler->display->display_options['arguments']['term_node_tid_depth']['default_action'] = 'default';
  $handler->display->display_options['arguments']['term_node_tid_depth']['title_enable'] = TRUE;
  $handler->display->display_options['arguments']['term_node_tid_depth']['title'] = 'Related Upcoming Events ';
  $handler->display->display_options['arguments']['term_node_tid_depth']['default_argument_type'] = 'taxonomy_tid';
  $handler->display->display_options['arguments']['term_node_tid_depth']['default_argument_options']['node'] = TRUE;
  $handler->display->display_options['arguments']['term_node_tid_depth']['default_argument_options']['anyall'] = '+';
  $handler->display->display_options['arguments']['term_node_tid_depth']['default_argument_options']['vocabularies'] = array(
      'stanford_related_content' => 'stanford_related_content',
  );
  $handler->display->display_options['arguments']['term_node_tid_depth']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['term_node_tid_depth']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['term_node_tid_depth']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['arguments']['term_node_tid_depth']['specify_validation'] = TRUE;
  $handler->display->display_options['arguments']['term_node_tid_depth']['depth'] = '0';
  $handler->display->display_options['arguments']['term_node_tid_depth']['break_phrase'] = TRUE;

  $handler->display->display_options['defaults']['footer'] = FALSE;
  /* Footer: Global: See more link */
  $handler->display->display_options['footer']['area']['id'] = 'area';
  $handler->display->display_options['footer']['area']['table'] = 'views';
  $handler->display->display_options['footer']['area']['field'] = 'area';
  $handler->display->display_options['footer']['area']['ui_name'] = 'Global: See more link';
  $handler->display->display_options['footer']['area']['content'] = '<a  href=\'term_node_tid_depth[0]=!1\' class=more-link>See more related events</a>';
  $handler->display->display_options['footer']['area']['format'] = 'content_editor_text_format';
  $handler->display->display_options['footer']['area']['tokenize'] = TRUE;
}

/*
 * Implements hook_views_pre_build().
 */
function stanford_related_events_views_pre_build(&$view) {
  if ($view->name == "stanford_events_views"){
    if (($view->current_display == "filtered_upcoming_block") ||
      ($view->current_display == "block_5")){
      $pattern = "/\[hook_views_pre_build:.*\]/";
      $subject = $view->footer["area"]->options["content"];
      $matches = array();
      preg_match($pattern, $subject, $matches);
      if (!empty($matches)){

        // Build the URL
        $parts = explode(":", $matches[0]);
        $url = str_replace("]","",$parts[1]);

        // Replace text with the URL
        $options = array('attributes' => array( 'class' => array('more-link')),
                         'query' => array(stanford_related_events_build_tax_args($view)));
        $a = l("See more related events", $url, $options);
        $subject = preg_replace($pattern, $a, $subject);
        $view->footer["area"]->options["content"] = $subject;
      }
    }
  }
}
/*
 * Build the terms into arguments for the url
 */
function stanford_related_events_build_tax_args($view) {
  if (arg(0) == 'node') {
    $nid = arg(1);
  }

  $result = array();
  $node = node_load($nid);
  if ($node) {
    foreach($node ->field_s_related_content['und'] as $key => $value) {
      $result['term_node_tid_depth[' . $key . ']'] = $value['tid'];
    }
  }
  return $result;
}

