<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_views_default_views_alter().
 */
function stanford_related_news_views_default_views_alter(&$views) {
  // What does this do? Needs comment here...
  stanford_related_news_alter_manage_news($views);
}

/**
 * Add exposed filter for related content to the page display.
 *
 * @param object $views
 *   Array of views.
 */
function stanford_related_news_alter_manage_news(&$views) {
  $view_name = 'admin_manage_stanford_news_item';
  if (array_key_exists($view_name, $views)) {
    $view = $views[$view_name];
  }
  else {
    return FALSE;
  }

  $display_name = 'page_1';
  if ($view->set_display($display_name)) {
    $handler = $view->display_handler;
  }
  else {
    watchdog('stanford_related_news', "Display %display_name not available in view %view_name.",
      array('%display_name' => $display_name, '%view_name' => $view_name), WATCHDOG_NOTICE);
    return FALSE;
  }

  // Add the exposed filter.
  return stanford_related_content_add_exposed_filter($views, $view_name, $display_name, FALSE, "Related Content");

}

/**
 * Implementation of hook_views_pre_view().
 */
function stanford_related_news_views_pre_view(&$view, &$display_id, &$args) {

  // Insert the related content field after the location field.
  if ($view->name == 'admin_manage_stanford_news_item' && $view->current_display == "page_1") {
    stanford_related_content_insert_related_content($view, $display_id, 'field_s_news_source');
  }

}
